# Generated by Django 4.2.3 on 2023-07-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane_id', models.CharField(max_length=8, unique=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('velocity', models.FloatField()),
                ('fuel', models.FloatField()),
                ('status', models.IntegerField(choices=[(1, 'Waiting'), (2, 'Approaching'), (3, 'Descending'), (4, 'Landed'), (5, 'Crashed')], default=1)),
            ],
        ),
    ]
