# Generated by Django 4.2.3 on 2023-07-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='airplane_id',
            field=models.CharField(max_length=8),
        ),
    ]
