# Generated by Django 4.2.3 on 2023-07-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0004_airplane_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='image',
        ),
        migrations.AddField(
            model_name='airplane',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
