# Generated by Django 4.2.3 on 2023-08-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport_app", "0005_remove_airplane_image_airplane_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image_size",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="airplane",
            name="image_x",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="airplane",
            name="image_y",
            field=models.IntegerField(default=0),
        ),
    ]
